Se entrega a mayores el Jupyter Notebook “limpieza-practica.ipynb”, se recomienda ejecutar esas líneas de código antes de resolver los ejercicios con el fin de preparar algunas de las variables que se usarán en las visualizaciones.

In [1]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('../../data/salaries.csv')
data

In [19]:
data['country'].unique()

array(['United States', 'United Kingdom', 'US', 'USA', 'Canada',
       'United Kingdom ', 'usa', 'UK', 'Scotland ', 'U.S.',
       'United States ', 'The Netherlands', 'Australia ', 'Spain', 'us',
       'Usa', 'England', 'finland', 'United States of America', 'France',
       'United states', 'Scotland', 'USA ', 'United states ', 'Germany',
       'UK ', 'united states', 'Ireland', 'Australia', 'Uk',
       'United States of America ', 'U.S. ', 'canada', 'Canada ', 'U.S>',
       'ISA', 'Great Britain ', 'US ', 'United State', 'U.S.A', 'Denmark',
       'U.S.A.', 'America', 'Netherlands', 'netherlands', 'England ',
       'united states of america', 'Ireland ', 'Switzerland',
       'Netherlands ', 'Bermuda', 'Us', 'The United States',
       'United State of America', 'Germany ', 'Mexico ', 'United Stated',
       'South Africa ', 'Belgium', 'Northern Ireland', 'u.s.',
       'South Africa', 'UNITED STATES', 'united States', 'Sweden',
       'Hong Kong', 'Kuwait', 'Sri lanka', 'Contracts',
       'USA-- Virgin Islands', 'United Statws', 'England/UK', 'U.S',
       "We don't get raises, we get quarterly bonuses, but they periodically asses income in the area you work, so I got a raise because a 3rd party assessment showed I was paid too little for the area we were located",
       'Unites States ', 'Usa ', 'U.S.A. ', 'England, UK.', 'Greece',
       'Japan', 'U. S. ', 'Britain ', 'United Sates', 'Japan ', 'Austria',
       'Canada, Ottawa, ontario', 'Global', 'Sweden ',
       'United States of American ', 'FRANCE', 'Uniited States',
       'United Kingdom (England)',
       'Worldwide (based in US but short term trips aroudn the world)',
       'CANADA ', 'Canadw', 'Luxembourg', 'United Sates of America',
       'ireland',
       'United States (I work from home and my clients are all over the US/Canada/PR',
       'Colombia', 'CANADA', 'Unted States', 'germany', 'United Statesp',
       'United Stattes', 'United Statea', 'United Kingdom.', 'Mexico',
       'New Zealand', 'Unites States', 'United Statees', 'United kingdom',
       'Cayman Islands', 'UNited States', 'Can',
       'I am located in Canada but I work for a company in the US',
       'United kingdom ', 'Uniyed states', 'Uniyes States',
       'United States of Americas', 'U.A.', 'Latvia', 'Finland', 'U. S.',
       'Puerto Rico', 'US of A', 'Rwanda', 'United States of america ',
       'United Arab Emirates ', 'Spain ', 'U.K. ', 'Romania', 'U.SA',
       'United Kindom', 'United Status', 'New Zealand ',
       'Currently finance', ' U.S.', 'Serbia', 'Russia ', 'UXZ',
       'England, UK', 'Canda', 'Puerto Rico ', 'Canada and USA',
       'Catalonia', '$2,175.84/year is deducted for benefits', 'uk',
       'France ', 'Italy (South)', 'Jersey, Channel islands', 'Uk ',
       'Virginia', 'Afghanistan', 'U.s.', 'Great Britain', 'U.s.a.',
       'USS', 'Uniteed States', 'New Zealand Aotearoa', 'U.K.',
       'Hartford', 'Japan, US Gov position', 'Csnada', 'United Stares',
       'New zealand', 'I.S.', 'UK (Northern Ireland)',
       'UK for U.S. company', ' US', 'Unites states ', 'NZ', 'Us ',
       'Hong Kong ', 'Canad', 'Unite States', 'australia', 'The US',
       'China', 'united states ', 'The Netherlands ', 'Cambodia',
       'United states of America ', 'Vietnam', 'Remote', 'India',
       'Bangladesh', 'Israel', 'Lithuania', 'Eritrea',
       'For the United States government, but posted overseas', 'IS',
       'Switzerland ', 'United Kingdomk', 'Italy', 'Norway',
       ' New Zealand', 'Cuba', 'Slovenia', 'Australi', "Cote d'Ivoire",
       'united kingdom', 'From Romania, but for an US based company',
       'Somalia', 'Wales (United Kingdom)', 'England, Gb', 'UnitedStates',
       'spain', 'Danmark', 'U.K. (northern England)', 'U.K', 'Malaysia',
       'NL', 'the Netherlands', 'Nederland', 'Slovakia',
       'United States of america', 'Portugal ', 'England, United Kingdom',
       'Sierra Leone', 'Englang', 'United statew', 'UAE', 'Belgium ',
       'Singapore',
       'bonus based on meeting yearly goals set w/ my supervisor',
       'International ', 'The Bahamas ', 'Wales',
       "I earn commission on sales. If I meet quota, I'm guaranteed another 16k min. Last year i earned an additional 27k. It's not uncommon for people in my space to earn 100k+ after commission. ",
       'Costa Rica', ' United States', 'United Statues', 'Argentina',
       'Untied States',
       'USA (company is based in a US territory, I work remote)', 'Chile',
       'denmark', 'UK (England)', 'UK, remote', 'Scotland, UK', 'USAB',
       'Unitied States', 'Norway ', 'Qatar', 'United Sttes', 'Hungary',
       'Remote (philippines)', 'Unites kingdom ', 'South africa',
       'Portugal', 'united stated', 'United States Of America', 'Nigeria',
       'Panamá', 'Northern Ireland ', 'england', 'SWITZERLAND', 'Brazil',
       'Austria, but I work remotely for a Dutch/British company',
       'I was brought in on this salary to help with the EHR and very quickly was promoted to current position but compensation was not altered. ',
       'Uniter Statez', 'U. S ', 'Congo', 'United states of America',
       'Uruguay', 'Pakistan', 'USA tomorrow ', 'United Stateds',
       'n/a (remote from wherever I want)', 'singapore',
       'US govt employee overseas, country withheld', 'usa ', 'Malaysia ',
       'Uganda', 'Philippines', 'Poland', 'Malta', 'Bulgaria', 'Estonia',
       'Morocco', 'new zealand', 'Africa', 'Ecuador', 'Zimbabwe', 'Ghana',
       'San Francisco', 'Usat', '🇺🇸 ', 'Luxemburg', 'Unitef Stated', 'UA',
       'Wales, UK', 'United Stares ', 'Croatia ',
       'England, United Kingdom ', 'United STates', 'USaa', 'uSA',
       'South Korea ', 'The netherlands', 'Ukraine ', 'america',
       'switzerland', 'United States- Puerto Rico',
       'From New Zealand but on projects across APAC', 'Y', 'United y',
       'Thailand', 'Wales (UK)', 'Isle of Man',
       'Northern Ireland, United Kingdom', 'europe', 'California ',
       'UK, but for globally fully remote company', 'Australian ',
       'Jamaica', 'uS', 'USD', 'the netherlands',
       "USA, but for foreign gov't", 'japan', 'Kenya', 'Jordan',
       'United Statss', 'United states of america', 'UsA',
       'I work for a UAE-based organization, though I am personally in the US.',
       'United  States', 'france', 'Aotearoa New Zealand', 'na', 'Policy',
       'Cyprus', 'hong konh', 'United States is America', 'Liechtenstein',
       'Company in Germany. I work from Pakistan.', 'Canadá', 'ENGLAND',
       'United States of American', 'U.S.A ', 'Bosnia and Herzegovina'],
      dtype=object)

In [ ]:

data = data.assign(
    fixed_country=data.country.str.lower().str.strip()
)

#UK
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("king"), "united kingdom", data.fixed_country)
)
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("uk"), "united kingdom", data.fixed_country)
)
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.replace(" ", "").str.startswith("u.k"), "united kingdom", data.fixed_country)
)
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.replace(" ", "").str.startswith("u.k"), "united kingdom", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("kindom"), "united kingdom", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("england"), "united kingdom", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("scot"), "united kingdom", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("britain"), "united kingdom", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("wales"), "united kingdom", data.fixed_country)
)


#US
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("state"), "united states", data.fixed_country)
)
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("america"), "united states", data.fixed_country)
)
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("us"), "united states", data.fixed_country)
)
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.replace(" ", "").str.startswith("u.s"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("isa"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("statws"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("status"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("sates"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("stattes"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("stares"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("status"), "united states", data.fixed_country)
)


data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("statss"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("i.s"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("is"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("the us"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("statues"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("sttes"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("us"), "united states", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("california"), "united states", data.fixed_country)
)
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("virginia"), "united states", data.fixed_country)
)
#Canada
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("canad"), "canada", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("canda"), "canada", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("cnada"), "canada", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("can"), "canada", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("csnada"), "canada", data.fixed_country)
)

#NL
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("nethe"), "netherland", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("nede"), "netherland", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("nl"), "netherland", data.fixed_country)
)
#HK
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("konh"), "hong kong", data.fixed_country)
)

#NZ
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("new z"), "new zealand", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("nz"), "new zealand", data.fixed_country)
)

#UAE

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("emirates"), "uae", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("ua"), "uae", data.fixed_country)
)

data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("u.a."), "uae", data.fixed_country)
)

#JAPAN
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("jap"), "japan", data.fixed_country)
)


#ITALY
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("ital"), "italy", data.fixed_country)
)

#AU
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.startswith("austra"), "australia", data.fixed_country)
)

#Spain
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("catalonia"), "spain", data.fixed_country)
)

#AU
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("remote"), "remote", data.fixed_country)
)

#AU
data = data.assign(
    fixed_country=np.where(data.fixed_country.str.contains("danmark"), "denmark", data.fixed_country)
)

In [78]:
data.fixed_country.value_counts().reset_index().head(20)['count'].sum() / data.shape[0]

np.float64(0.9949547731449782)

In [79]:
fixed_country=data['fixed_country'].unique()
fixed_country

array(['united states', 'united kingdom', 'canada', 'netherland',
       'australia', 'spain', 'finland', 'france', 'germany', 'ireland',
       'denmark', 'switzerland', 'bermuda', 'mexico', 'south africa',
       'belgium', 'northern ireland', 'sweden', 'hong kong', 'uae',
       'sri lanka', 'contracts', 'greece', 'japan', 'austria', 'global',
       'luxembourg', 'colombia', 'new zealand', 'latvia', 'puerto rico',
       'rwanda', 'romania', 'currently finance', 'serbia', 'russia',
       'uxz', 'italy', 'hartford', 'china', 'cambodia', 'vietnam',
       'remote', 'india', 'bangladesh', 'lithuania', 'eritrea', 'norway',
       'cuba', 'slovenia', "cote d'ivoire",
       'from romania, but for an us based company', 'somalia', 'malaysia',
       'slovakia', 'sierra leone', 'englang', 'singapore',
       'international', 'the bahamas', 'costa rica', 'argentina', 'chile',
       'qatar', 'hungary', 'nigeria', 'panamá', 'brazil', 'congo',
       'uruguay', 'philippines', 'poland', 'malta', 'bulgaria', 'estonia',
       'morocco', 'africa', 'ecuador', 'zimbabwe', 'ghana', '🇺🇸',
       'luxemburg', 'croatia', 'south korea', 'y', 'united y', 'thailand',
       'europe', 'jamaica', 'kenya', 'jordan', 'na', 'policy', 'cyprus',
       'liechtenstein', 'bosnia and herzegovina'], dtype=object)

In [5]:
data.head()

,age,industry,title,annual_salary,bonus_salary,currency,country,state,city,overall_experience,field_experience,education,gender,fixed_country
0,25-34,Education (Higher Education),Research and Instruction Librarian,55000.0,0.0,USD,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,united states
1,25-34,Computing or Tech,Change & Internal Communications Manager,54600.0,4000.0,GBP,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,united kingdom
2,25-34,"Accounting, Banking & Finance",Marketing Specialist,34000.0,NaN,USD,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,united states
3,25-34,Nonprofits,Program Manager,62000.0,3000.0,USD,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,united states
4,25-34,"Accounting, Banking & Finance",Accounting Manager,60000.0,7000.0,USD,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,united states

## Ejercicio 1 – Preparación de datos

Queremos formatear los datos correctamente para prepararlos de cara a las visualizaciones solicitadas en los siguientes ejercicios. Para ello, se pide:

* Leer los sets de datos proporcionados
* Aplicar el tipo de cambio a las columnas de salario y bonus para que todo quede representado en USD
* Eliminar datos con poca muestra que introducen ruido:

* Registros de las edades "under 18" y "65 or over".
* Registros con salarios anuales (sin bonus) por encima de los 200K dólares.
* Registros con géneros distintos a "Man" o "Woman".
* Imputar los valores faltantes (si los hay) de salario y bonus a 0.

Leemos el fichero exchange_rates.csv

In [4]:
fx= pd.read_csv('../../data/exchange_rates.csv')
fx.head()

  currency  exchange_rate
0      AUD       0.671307
1      CAD       0.750496
2      CHF       1.058380
3      EUR       1.039290
4      GBP       1.191120

Hacemos un join donde nos traemos el tipo de cambio en funcion de la divisa.
### Ver si se puede hacer de otra manera, sin tener qu hacer un join. Simplemente multiplicando columnas de dos dataframes??

In [7]:
data_usd=pd.merge(
    data,
    fx,
    on='currency',
    how='left'
)

In [ ]:
data_usd

Creamos dos columnas nuevas, donde convertimos a USD el salario y el bonus anual.

In [9]:
data_usd['annual_salary_usd']=data_usd['annual_salary']*data_usd['exchange_rate'] 
data_usd['bonus_salary_usd']=data_usd['bonus_salary']*data_usd['exchange_rate'] 
data_usd['salary_bonus_usd']=(data_usd['bonus_salary']+data_usd['annual_salary'])*data_usd['exchange_rate']

Para elimninar los datos

In [31]:
data_usd['age'].unique()

array(['25-34', '45-54', '35-44', '18-24', '65 or over', '55-64',
       'under 18'], dtype=object)

In [32]:
data_usd['gender'].unique()

array(['Woman', 'Non-binary', 'Man', nan, 'Other or prefer not to answer',
       'Prefer not to answer'], dtype=object)

In [11]:
data_filtered = data_usd[
    (~data_usd['age'].isin(['under 18', '65 or over'])) &
    (data_usd['annual_salary_usd'] <= 200000) &
    (data_usd['gender'].isin(['Man', 'Woman']))
]

In [ ]:
data_filtered

In [ ]:
#data_filtered['annual_salary'] = data_filtered['annual_salary'].fillna(0)
#data_filtered['bonus_salary'] = data_filtered['bonus_salary'].fillna(0)
#data_filtered['annual_salary_usd'] = data_filtered['annual_salary_usd'].fillna(0)
#data_filtered['bonus_salary_usd'] = data_filtered['bonus_salary_usd'].fillna(0)
#data_filtered['salary_bonus_usd'] = data_filtered['salary_bonus_usd'].fillna(0)

In [15]:
data_filtered.loc[:, 'annual_salary'] = data_filtered['annual_salary'].fillna(0)
data_filtered.loc[:, 'bonus_salary'] = data_filtered['bonus_salary'].fillna(0)
data_filtered.loc[:, 'annual_salary_usd'] = data_filtered['annual_salary_usd'].fillna(0)
data_filtered.loc[:, 'bonus_salary_usd'] = data_filtered['bonus_salary_usd'].fillna(0)
data_filtered.loc[:, 'salary_bonus_usd'] = data_filtered['salary_bonus_usd'].fillna(0)

## Ejercicio 2 – Salario + bonus medio por país
Queremos mostrar en un gráfico el salario + bonus medio que se tiene en cada país obtenido sobre los datos preparados en el ejercicio 1. Para ello:

Datos:

* Calcula el salario + bonus medio de cada uno de los países.
* Si son más de 8 países, quédate únicamente con el top 8 en términos de salario + bonus medio.

In [12]:
import matplotlib.pyplot as plt
import plotnine as p9

ModuleNotFoundError: No module named 'plotnine'

In [17]:
df_ej2=(
    data_filtered.groupby(['fixed_country'])[['annual_salary_usd','bonus_salary_usd']]
    .mean()
    .reset_index()
    .sort_values(by='annual_salary_usd', ascending=False)
    .head(8)
)

df_ej2

      fixed_country  annual_salary_usd  bonus_salary_usd
138            u.a.          198000.00            5000.0
7        australian          195000.00           15000.0
148  united stattes          190000.00           30000.0
88    liechtenstein          160873.76               0.0
131       sri lanka          160000.00               0.0
97        nederland          155893.50               0.0
149  united statues          152800.00            6068.0
125        slovakia          145500.60               0.0

In [ ]:
ggplot(diamonds, aes(x='carat', y='price')) + geom_point()